package service

// 由改造前的实现（HEAD 52a8320）生成，见 subscription_pattern_pin_test.go 顶部说明。不要手改。
// 唯一的手改是 subpath-depend 的 managed / candidates（有意修正的旧缺陷），见该条注释。

var subscriptionPinGolden = map[string]subscriptionPinResult{
	"ql-plain": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "**/*jx_*", "**/*jx_*/**", "**/*jddj_*", "**/*jddj_*/**", "**/*USER*", "**/*USER*/**", "**/*JD*", "**/*JD*/**", "**/*function*", "**/*function*/**", "**/*sendNotify*", "**/*sendNotify*/**", "**/*utils*", "**/*utils*/**", "!**/*backUp*", "!**/*backUp*/**"},
		warningTags:             []string{"[依赖规则]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js"},
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jd_group/helper.js"},
		depend:                  []string{"sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js"},
		dependOnly:              []string{"sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js"},
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jd_group/helper.js"},
		candidates:              []string{"task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js"},
		scanDependOnly:          []string{"JD_UPPER.JS", "JD_helper.js", "JS_USER_AGENTS.js", "function_box.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js"},
	},
	"ql-whitelist-blacklist": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "**/*jx_*", "**/*jx_*/**", "**/*jddj_*", "**/*jddj_*/**", "!**/*backUp*", "!**/*backUp*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js"},
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jd_group/helper.js"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jd_group/helper.js"},
		candidates:              []string{"task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js"},
		scanDependOnly:          []string(nil),
	},
	"comma": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "**/*jx_*", "**/*jx_*/**", "**/*jddj_*", "**/*jddj_*/**", "!**/*backUp*", "!**/*backUp*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js"},
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jd_group/helper.js"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jd_group/helper.js"},
		candidates:              []string{"task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js"},
		scanDependOnly:          []string(nil),
	},
	"spaces-and-empty-segments": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "**/*jx_*", "**/*jx_*/**", "!**/*jd_old*", "!**/*jd_old*/**", "!**/*Archive*", "!**/*Archive*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "Archive/b.js"},
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		candidates:              []string{"task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jx_sign.js"},
		scanDependOnly:          []string(nil),
	},
	"glob-star": {
		patterns:                []string{"**/*jd_*.js*", "**/*jd_*.js*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string(nil),
		blacklistExcluded:       []string(nil),
		filters:                 []string(nil),
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string(nil),
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"glob-ext": {
		patterns:                []string{"**/**.js*", "**/**.js*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string(nil),
		blacklistExcluded:       []string(nil),
		filters:                 []string(nil),
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string(nil),
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"single-keep": {
		patterns:                []string{"**/*keep_task*", "**/*keep_task*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"scripts/daily/keep_task.py", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"scripts/daily/keep_task.py", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"scripts/daily/keep_task.py", "keep_task.py"},
		candidates:              []string{"task pin-repo/keep_task.py", "task pin-repo/scripts/daily/keep_task.py"},
		scanDependOnly:          []string(nil),
	},
	"blacklist-only": {
		patterns:                []string{"*", "!**/*backUp*", "!**/*backUp*/**", "!**/*Archive*", "!**/*Archive*/**", "!**/*.github*", "!**/*.github*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js", ".github/workflows/c.yml", "Archive/b.js"},
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "jd_group/helper.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "jd_group/helper.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	// subpath-depend 的 managed / candidates 是有意的修正，不再是 HEAD 52a8320 的输出：普通依赖片段并进子目录的
	// sparse 规则后，子目录外命中依赖规则的文件会落盘；改造前那里没有子目录护栏，白名单留空时它们会被建成定时任务
	// （真机 git 复现见 subscription_subpath_depend_scope_test.go）。其余字段仍是原样。
	"subpath-depend": {
		patterns:                []string{"scripts/daily", "**/*sendNotify*", "**/*sendNotify*/**"},
		warningTags:             []string{"[依赖规则]"},
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string{"sendNotify.js"},
		dependOnly:              []string(nil),
		managed:                 []string{"scripts/daily/keep.js", "scripts/daily/keep_task.py"},
		candidates:              []string{"task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py"},
		scanDependOnly:          []string(nil),
	},
	"subpath-multi-whitelist": {
		patterns:                []string{"scripts/daily", "tools"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		candidates:              []string{"task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js"},
		scanDependOnly:          []string(nil),
	},
	"subpath-trailing-slash": {
		patterns:                []string{"scripts/daily/"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"scripts/daily/keep.js", "scripts/daily/keep_task.py", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"scripts/daily/keep.js", "scripts/daily/keep_task.py", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"scripts/daily/keep.js", "scripts/daily/keep_task.py", "keep_task.py"},
		candidates:              []string{"task pin-repo/keep_task.py", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py"},
		scanDependOnly:          []string(nil),
	},
	"subpath-risky": {
		patterns:                []string{"*", "!**/*backUp*", "!**/*backUp*/**"},
		warningTags:             []string{"[警告]"},
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js"},
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "jd_group/helper.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "jd_group/helper.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"subpath-risky-depend": {
		patterns:                []string(nil),
		warningTags:             []string{"[警告]", "[提示]"},
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string{"sendNotify.js"},
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"whitelist-depend-overlap": {
		patterns:                []string{"**/*utils*", "**/*utils*/**", "**/*sendNotify*", "**/*sendNotify*/**"},
		warningTags:             []string{"[依赖规则]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"utils/date.js", "utils/nested/http.js"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"utils/date.js", "utils/nested/http.js"},
		depend:                  []string{"sendNotify.js", "utils/date.js", "utils/nested/http.js"},
		dependOnly:              []string{"sendNotify.js"},
		managed:                 []string{"utils/date.js", "utils/nested/http.js"},
		candidates:              []string{"task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js"},
		scanDependOnly:          []string{"sendNotify.js"},
	},
	"wildcard-star": {
		patterns:                []string(nil),
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"wildcard-all": {
		patterns:                []string(nil),
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"wildcard-mixed": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"wildcard-dot-star": {
		patterns:                []string(nil),
		warningTags:             []string{"[提示]"},
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string{"sendNotify.js"},
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"depend-note": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**"},
		warningTags:             []string{"[提示]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		candidates:              []string{"task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js"},
		scanDependOnly:          []string(nil),
	},
	"depend-half-note": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "**/*sendNotify*", "**/*sendNotify*/**"},
		warningTags:             []string{"[依赖规则]", "[提示]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		depend:                  []string{"sendNotify.js"},
		dependOnly:              []string{"sendNotify.js"},
		managed:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		candidates:              []string{"task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js"},
		scanDependOnly:          []string{"sendNotify.js"},
	},
	"depend-long-note": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**"},
		warningTags:             []string{"[提示]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		candidates:              []string{"task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js"},
		scanDependOnly:          []string(nil),
	},
	"normalization-prefix": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "**/*jx_*", "**/*jx_*/**", "**/*utils/*", "**/*utils/*/**", "!**/*backUp*", "!**/*backUp*/**"},
		warningTags:             []string{"[依赖规则]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js"},
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jd_group/helper.js"},
		depend:                  []string{"utils/date.js", "utils/nested/http.js"},
		dependOnly:              []string{"utils/date.js", "utils/nested/http.js"},
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jd_group/helper.js"},
		candidates:              []string{"task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jx_sign.js"},
		scanDependOnly:          []string{"utils/date.js", "utils/nested/http.js"},
	},
	"normalization-dot-slash-star": {
		patterns:                []string(nil),
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string(nil),
		blacklistExcluded:       []string(nil),
		filters:                 []string(nil),
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string(nil),
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"plain-plus-dot": {
		patterns:                []string{"**/*c++*", "**/*c++*/**", "**/*a.b*", "**/*a.b*/**", "**/*x+y*", "**/*x+y*/**", "**/*jd+*", "**/*jd+*/**", "!**/*node_modules*", "!**/*node_modules*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"c++/a.js", "a.b.js", "x+y.js", "jd+x.js"},
		blacklistExcluded:       []string{"node_modules/x.js"},
		filters:                 []string{"c++/a.js", "a.b.js", "x+y.js", "jd+x.js"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"c++/a.js", "a.b.js", "x+y.js", "jd+x.js"},
		candidates:              []string{"task pin-repo/a.b.js", "task pin-repo/c++/a.js", "task pin-repo/jd+x.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"depend-wildcard": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "**/*sendNotify*", "**/*sendNotify*/**"},
		warningTags:             []string{"[依赖规则]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		depend:                  []string{"sendNotify.js"},
		dependOnly:              []string{"sendNotify.js"},
		managed:                 []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		candidates:              []string{"task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js"},
		scanDependOnly:          []string{"sendNotify.js"},
	},
	"full-checkout-subpath": {
		patterns:                []string(nil),
		warningTags:             []string{"[提示]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"qinglong/DefaultTasks/bili_task_manga.sh"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js"},
		filters:                 []string{"qinglong/DefaultTasks/bili_task_manga.sh"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"qinglong/DefaultTasks/bili_task_manga.sh"},
		candidates:              []string{"task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh"},
		scanDependOnly:          []string(nil),
	},
	"full-checkout-subpath-only": {
		patterns:                []string(nil),
		warningTags:             []string{"[提示]"},
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"qinglong/DefaultTasks/bili_task_manga.sh"},
		candidates:              []string{"task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh"},
		scanDependOnly:          []string(nil),
	},
	"full-checkout-bare": {
		patterns:                []string(nil),
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string{"sendNotify.js"},
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"depend-only": {
		patterns:                []string(nil),
		warningTags:             []string{"[提示]"},
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string{"sendNotify.js", "utils/date.js", "utils/nested/http.js"},
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"whitelist-blacklist-depend": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "**/*sendNotify*", "**/*sendNotify*/**", "!**/*backUp*", "!**/*backUp*/**"},
		warningTags:             []string{"[依赖规则]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js"},
		filters:                 []string{"jd_bean_change.js", "jd_group/helper.js"},
		depend:                  []string{"sendNotify.js"},
		dependOnly:              []string{"sendNotify.js"},
		managed:                 []string{"jd_bean_change.js", "jd_group/helper.js"},
		candidates:              []string{"task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/helper.js"},
		scanDependOnly:          []string{"sendNotify.js"},
	},
	"whitelist-dir-path": {
		patterns:                []string{"**/*scripts/daily*", "**/*scripts/daily*/**", "!**/*scripts/other*", "!**/*scripts/other*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"scripts/daily/keep.js", "scripts/daily/keep_task.py"},
		blacklistExcluded:       []string{"scripts/other/skip.js"},
		filters:                 []string{"scripts/daily/keep.js", "scripts/daily/keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"scripts/daily/keep.js", "scripts/daily/keep_task.py"},
		candidates:              []string{"task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py"},
		scanDependOnly:          []string(nil),
	},
	"whitelist-equals-blacklist": {
		patterns:                []string{"**/*jd_*", "**/*jd_*/**", "!**/*jd_*", "!**/*jd_*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		blacklistExcluded:       []string{"jd_bean_change.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js"},
		filters:                 []string(nil),
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string(nil),
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"whitelist-case-sensitive": {
		patterns:                []string{"**/*JD_*", "**/*JD_*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string{"JD_helper.js", "JD_UPPER.JS"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"JD_helper.js", "JD_UPPER.JS"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"JD_helper.js", "JD_UPPER.JS"},
		candidates:              []string{"task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js"},
		scanDependOnly:          []string(nil),
	},
	"whitelist-no-match": {
		patterns:                []string{"**/*definitely_not_here*", "**/*definitely_not_here*/**", "**/*sendNotify*", "**/*sendNotify*/**", "**/*utils*", "**/*utils*/**"},
		warningTags:             []string{"[依赖规则]"},
		hasNonWildcardWhitelist: true,
		whitelist:               []string(nil),
		blacklistExcluded:       []string(nil),
		filters:                 []string(nil),
		depend:                  []string{"sendNotify.js", "utils/date.js", "utils/nested/http.js"},
		dependOnly:              []string{"sendNotify.js", "utils/date.js", "utils/nested/http.js"},
		managed:                 []string(nil),
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/tools/build.sh", "task pin-repo/x+y.js"},
		scanDependOnly:          []string{"sendNotify.js", "utils/date.js", "utils/nested/http.js"},
	},
	"whitelist-no-match-blacklist": {
		patterns:                []string{"**/*definitely_not_here*", "**/*definitely_not_here*/**", "!**/*backUp*", "!**/*backUp*/**"},
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: true,
		whitelist:               []string(nil),
		blacklistExcluded:       []string{"backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/backUp/old.js"},
		filters:                 []string(nil),
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string(nil),
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
	"empty": {
		patterns:                []string(nil),
		warningTags:             []string(nil),
		hasNonWildcardWhitelist: false,
		whitelist:               []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		blacklistExcluded:       []string(nil),
		filters:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "README.md", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", ".github/workflows/c.yml", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		depend:                  []string(nil),
		dependOnly:              []string(nil),
		managed:                 []string{"jd_bean_change.js", "jx_sign.js", "jddj_bean.js", "jdCookie.js", "sendNotify.js", "utils/date.js", "utils/nested/http.js", "JS_USER_AGENTS.js", "JD_helper.js", "JD_UPPER.JS", "function_box.js", "other_task.js", "backUp/jd_old.js", "backUp/nested/jd_older.js", "jd_group/helper.js", "jd_group/backUp/old.js", "scripts/daily/keep.js", "scripts/daily/keep_task.py", "scripts/other/skip.js", "scripts/jdCookie.js", "tools/build.sh", "qinglong/DefaultTasks/bili_task_manga.sh", "qinglong/DefaultTasksExtra/x.sh", "Archive/b.js", "node_modules/x.js", "c++/a.js", "a.b.js", "x+y.js", "jd+x.js", "keep_task.py"},
		candidates:              []string{"task pin-repo/Archive/b.js", "task pin-repo/JD_UPPER.JS", "task pin-repo/JD_helper.js", "task pin-repo/JS_USER_AGENTS.js", "task pin-repo/a.b.js", "task pin-repo/backUp/jd_old.js", "task pin-repo/backUp/nested/jd_older.js", "task pin-repo/c++/a.js", "task pin-repo/function_box.js", "task pin-repo/jd+x.js", "task pin-repo/jdCookie.js", "task pin-repo/jd_bean_change.js", "task pin-repo/jd_group/backUp/old.js", "task pin-repo/jd_group/helper.js", "task pin-repo/jddj_bean.js", "task pin-repo/jx_sign.js", "task pin-repo/keep_task.py", "task pin-repo/other_task.js", "task pin-repo/qinglong/DefaultTasks/bili_task_manga.sh", "task pin-repo/qinglong/DefaultTasksExtra/x.sh", "task pin-repo/scripts/daily/keep.js", "task pin-repo/scripts/daily/keep_task.py", "task pin-repo/scripts/jdCookie.js", "task pin-repo/scripts/other/skip.js", "task pin-repo/sendNotify.js", "task pin-repo/tools/build.sh", "task pin-repo/utils/date.js", "task pin-repo/utils/nested/http.js", "task pin-repo/x+y.js"},
		scanDependOnly:          []string(nil),
	},
}
